"""Inicial

Revision ID: 6b77b82eff32
Revises: 
Create Date: 2025-07-14 21:13:00.338525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b77b82eff32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casilleros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ubicacion', sa.String(), nullable=False),
    sa.Column('equipamento', sa.String(), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('humedad', sa.Float(), nullable=True),
    sa.Column('objeto_detectado', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('cedula', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('email')
    )
    op.create_table('prescripciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('lugar', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(length=6), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('prescripcion_id', sa.Integer(), nullable=False),
    sa.Column('casillero_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['casillero_id'], ['casilleros.id'], ),
    sa.ForeignKeyConstraint(['prescripcion_id'], ['prescripciones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prescripcion_id')
    )
    op.create_index(op.f('ix_data_id'), 'data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_id'), table_name='data')
    op.drop_table('citas')
    op.drop_table('prescripciones')
    op.drop_table('usuarios')
    op.drop_table('casilleros')
    # ### end Alembic commands ###
