"""agregar campo humedad en tabla data

Revision ID: b7f812bb288f
Revises: 6b77b82eff32
Create Date: 2025-07-18 19:27:35.757368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f812bb288f'
down_revision: Union[str, Sequence[str], None] = '6b77b82eff32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('humidity', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'humidity')
    # ### end Alembic commands ###
